import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";

export const metadata = {
  title: "Partner Terms & Conditions | NexaHome",
  description:
    "NexaHome Partner Terms & Conditions — the legally binding agreement governing your access to and use of the NexaHome Partner Dashboard and referral tools.",
};

export default function PartnerTermsAndConditionsPage() {
  return (
    <>
      <Navbar />
      {/* Hero Banner */}
      <div className="bg-primary text-white py-14 px-4">
        <div className="max-w-7xl mx-auto">
          <p className="text-sm uppercase tracking-widest text-white/60 font-medium mb-2">
            NexaHome, LLC
          </p>
          <h1 className="text-3xl md:text-4xl font-bold mb-3">
            Partner Terms &amp; Conditions
          </h1>
          <p className="text-white/70 text-sm">Effective Date: July 8, 2026</p>
        </div>
      </div>

      <main className="max-w-7xl mx-auto px-4 md:px-0 py-14">
        <section className="space-y-12 text-gray-600 leading-relaxed text-[15px]">

          {/* Section 1 */}
          <div>
            <SectionTitle number="1" title="Agreement to Terms" />
            <p className="mb-4">
              These Partner Terms and Conditions (&ldquo;Partner Terms&rdquo;) constitute a legally binding agreement
              between you (&ldquo;Partner,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and NexaHome, LLC (&ldquo;NexaHome,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo;
              or &ldquo;our&rdquo;), governing your access to and use of the NexaHome Partner Dashboard,
              referral tools, analytics and commission reporting features, and all related web-based services (collectively, the &ldquo;Partner Platform&rdquo;).
            </p>
            <p className="mb-4">
              These Partner Terms are separate from any executed Partner Agreement (or other commercial agreement addressing commissions or revenue sharing)
              entered into between you and NexaHome. In the event of any conflict between these Partner Terms and an executed written agreement relating
              specifically to commissions or revenue sharing, the executed written agreement shall control solely with respect to those commercial provisions.
            </p>
            <div className="bg-primary/10 border border-primary/20 text-primary font-semibold text-sm px-4 py-3 rounded-lg uppercase tracking-wide mb-4">
              BY CREATING A PARTNER ACCOUNT, ACCESSING THE PARTNER PLATFORM, OR PARTICIPATING IN THE NEXAHOME PARTNER PROGRAM, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE PARTNER TERMS AND THE PARTNER PRIVACY POLICY, WHICH IS INCORPORATED HEREIN BY REFERENCE. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT CREATE A PARTNER ACCOUNT OR USE THE PARTNER PLATFORM.
            </div>
            <p>
              You represent that you are at least eighteen (18) years of age and have the legal authority to enter into this Agreement on behalf of yourself or the organization you represent.
            </p>
          </div>

          <Divider />

          {/* Section 2 */}
          <div>
            <SectionTitle number="2" title="Description of the Partner Program" />
            <p className="mb-4">
              NexaHome operates a centralized technology platform that connects homeowners, renters, property managers, and other individuals seeking home services (&ldquo;Users&rdquo;) with independent service providers (&ldquo;Experts&rdquo;).
            </p>
            <p className="mb-4">
              The NexaHome Partner Program enables approved organizations, businesses, associations, lenders, brokers, builders, real estate professionals, and other approved referral partners to introduce new Users to the NexaHome Platform through Partner-specific referral links, invitation codes, or other approved referral methods.
            </p>
            <p className="mb-3">
              Partners receive access to a private web-based dashboard that allows them to:
            </p>
            <ul className="space-y-2 pl-1 mb-6">
              {[
                "Generate and manage referral links",
                "Invite Users to join NexaHome",
                "View referral activity and performance metrics",
                "Monitor service request activity generated by referred Users",
                "Review commission reports",
                "View payout history and related financial reporting",
                "Access marketing resources and Partner communications",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-4">
              The Partner Platform is provided solely to facilitate participation in the NexaHome Partner Program. Nothing within the Partner Platform grants Partners ownership of the NexaHome marketplace, Users, Experts, referral data, intellectual property, or Platform technology.
            </p>
            <p className="mb-3">
              NexaHome remains the sole owner and operator of the Platform and retains exclusive authority over:
            </p>
            <ul className="space-y-2 pl-1">
              {[
                "User registration",
                "Expert registration and verification",
                "Lead generation",
                "Lead distribution",
                "Credit pricing",
                "Marketplace operation",
                "Referral attribution",
                "Platform policies",
                "Revenue calculations",
                "Commission eligibility",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <Divider />

          {/* Section 3 */}
          <div>
            <SectionTitle number="3" title="Eligibility" />
            <p className="mb-3">
              Participation in the Partner Program is subject to NexaHome&rsquo;s approval. To maintain eligibility, you represent and warrant that:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "You are at least eighteen (18) years of age",
                "You possess the legal capacity to enter into binding contracts",
                "If acting on behalf of an organization, you possess authority to bind that organization",
                "All registration information provided is truthful, complete, and current",
                "You will maintain accurate business, payment, and tax information",
                "You will comply with all applicable federal, state, and local laws",
                "You will comply with these Partner Terms and all other policies published by NexaHome",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              NexaHome reserves the right, in its sole discretion, to approve, deny, suspend, or terminate any Partner application for any lawful reason. Approval into the Partner Program does not create any guarantee regarding referral volume, commissions, earnings, duration of participation, or continued access to the Partner Platform.
            </p>
          </div>

          <Divider />

          {/* Section 4 */}
          <div>
            <SectionTitle number="4" title="Partner Accounts" />

            <SubTitle>4.1 Registration</SubTitle>
            <p className="mb-3">
              To access the Partner Platform, you must register for a Partner account using information requested by NexaHome. Depending on your organization, registration may require:
            </p>
            <ul className="space-y-2 pl-11 mb-4">
              {[
                "Legal business name",
                "Contact person’s name",
                "Business address",
                "Email address",
                "Telephone number",
                "Organization type",
                "Tax information",
                "Banking or Stripe payout information",
                "Website information",
                "Additional documentation requested by NexaHome",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="pl-11 mb-6">
              You agree to provide only accurate and complete information and to promptly update any information that changes.
            </p>

            <SubTitle>4.2 Account Security</SubTitle>
            <p className="pl-11 mb-6">
              You are solely responsible for maintaining the confidentiality of your login credentials. You are responsible for all activities occurring under your account, whether or not authorized by you. You agree to notify NexaHome immediately if you suspect unauthorized access to your account. NexaHome shall not be liable for any loss resulting from unauthorized use of your credentials.
            </p>

            <SubTitle>4.3 Authorized Users</SubTitle>
            <p className="pl-11 mb-6">
              If your organization permits multiple employees or representatives to access the Partner Platform, you remain fully responsible for all activity performed under your organization’s account. You are responsible for ensuring that all authorized users comply with these Partner Terms.
            </p>

            <SubTitle>4.4 Account Suspension</SubTitle>
            <p className="pl-11 mb-3">
              NexaHome may suspend or restrict access to the Partner Platform at any time if we reasonably believe:
            </p>
            <ul className="space-y-2 pl-[54px]">
              {[
                "your account has been compromised",
                "fraudulent activity is suspected",
                "inaccurate information has been provided",
                "applicable laws require suspension",
                "these Partner Terms have been violated",
                "continued access may harm NexaHome, Users, Experts, or other Partners",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <Divider />

          {/* Section 5 */}
          <div>
            <SectionTitle number="5" title="Partner Dashboard" />
            <p className="mb-3">
              Approved Partners receive access to a secure, web-based Partner Dashboard. The Partner Dashboard is provided solely for informational and administrative purposes. Subject to Platform availability, the dashboard may display information including:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "Number of referred Users",
                "Referral growth trends",
                "Service request activity",
                "Commission summaries",
                "Estimated earnings",
                "Payout history",
                "Referral link management",
                "Marketing resources",
                "Account settings",
                "Platform announcements",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-6">
              Dashboard information is provided for convenience only. NexaHome does not guarantee that dashboard information will always be real-time, uninterrupted, error-free, or complete. If any discrepancy exists between dashboard information and NexaHome’s internal accounting records, NexaHome’s internal records shall control.
            </p>
            <p className="mb-3">
              Partners may not:
            </p>
            <ul className="space-y-2 pl-1">
              {[
                "modify dashboard functionality",
                "attempt to access restricted areas",
                "reverse engineer the dashboard",
                "interfere with reporting systems",
                "export data through unauthorized means",
                "scrape, harvest, or copy dashboard information using automated software",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <Divider />

          {/* Section 6 */}
          <div>
            <SectionTitle number="6" title="Referral Links and Invite Codes" />
            <p className="mb-4">
              NexaHome may assign Partners one or more referral links, invitation codes, QR codes, campaign identifiers, or similar tracking methods (collectively, &ldquo;Referral Identifiers&rdquo;). Referral Identifiers remain the exclusive property of NexaHome. Partners are granted a limited, revocable, non-exclusive, non-transferable license to use Referral Identifiers solely for participation in the NexaHome Partner Program.
            </p>
            <p className="mb-3">
              Partners shall not:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "modify Referral Identifiers",
                "create unauthorized referral systems",
                "manipulate referral tracking",
                "sublicense Referral Identifiers",
                "sell Referral Identifiers",
                "distribute Referral Identifiers through unlawful, deceptive, or misleading marketing practices",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Partners are solely responsible for safeguarding Referral Identifiers and ensuring they are used only for legitimate referral activities. NexaHome reserves the right to modify, replace, suspend, or revoke any Referral Identifier at any time.
            </p>
          </div>

          <Divider />

          {/* Section 7 */}
          <div>
            <SectionTitle number="7" title="Referral Attribution" />
            <p className="mb-4">
              Referral attribution is determined exclusively through NexaHome&rsquo;s internal tracking systems. A User will be considered attributed to a Partner only when NexaHome successfully records the applicable Referral Identifier during the User&rsquo;s initial account creation. Referral attribution may not be manually modified except by NexaHome.
            </p>
            <p className="mb-3">
              Partners acknowledge that:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "improperly distributed referral links may fail to track",
                "Users who register without a Referral Identifier may not be attributed",
                "duplicate accounts may not qualify",
                "fraudulent accounts are excluded",
                "deleted accounts may not qualify",
                "NexaHome’s attribution records are final except in cases of manifest error",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              NexaHome has no obligation to manually assign referrals that were not properly tracked during registration.
            </p>
          </div>

          <Divider />

          {/* Section 8 */}
          <div>
            <SectionTitle number="8" title="Revenue Share Overview" />
            <p className="mb-4">
              You earn a commission when an Expert (service provider) purchases a lead that was generated by a User who signed up through your referral link or code. In other words, when a User you referred submits a job request and an Expert pays credits to access that lead, you earn a commission on the resulting credit revenue.
            </p>
            <p className="mb-4">
              Eligible Partners may receive commissions pursuant to their executed Partner Agreement. Unless otherwise provided in a separate written agreement executed by NexaHome, eligible commissions are calculated based upon fifteen percent (15%) of qualifying Gross Credit Revenue generated from eligible Credit Purchases attributable to referred Users, as determined exclusively by NexaHome&rsquo;s tracking systems.
            </p>
            <p className="mb-4">
              Commission eligibility is governed by the applicable executed Partner Agreement. The Partner Dashboard may display estimated earnings and projected commission information; however, such information is informational only and does not constitute an obligation to pay any amount until commissions have been finalized under NexaHome&rsquo;s internal accounting procedures.
            </p>
            <p className="mb-3">
              Nothing within these Partner Terms guarantees:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "any minimum earnings",
                "any minimum number of referrals",
                "any level of Platform activity",
                "any commission amount",
                "continued participation in the Partner Program",
                "future commission opportunities",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              All commission calculations, adjustments, offsets, reversals, and payout determinations remain subject to NexaHome&rsquo;s Partner Agreement, fraud review procedures, refund policies, and applicable laws.
            </p>
          </div>

          <Divider />

          {/* Section 9 */}
          <div>
            <SectionTitle number="9" title="Stripe Connect, Payment Information, and Payouts" />

            <SubTitle>9.1 Stripe Connect</SubTitle>
            <p className="pl-11 mb-6">
              Participation in the NexaHome Partner Program may require you to establish and maintain a valid Stripe Connect account or another payment account designated by NexaHome. You acknowledge that Stripe is an independent third-party payment processor and that your use of Stripe’s services is governed solely by Stripe’s applicable agreements, policies, and privacy practices. NexaHome is not responsible for the operation, availability, security, or performance of Stripe’s services.
            </p>

            <SubTitle>9.2 Payment Information</SubTitle>
            <p className="pl-11 mb-6">
              You agree to provide accurate, complete, and current payment and tax information necessary to facilitate commission payments. Failure to provide or maintain accurate payment information may delay, suspend, or prevent commission payouts. NexaHome shall have no liability for payment delays resulting from inaccurate banking information, incomplete tax documentation, payment processor issues, governmental holds, or compliance reviews.
            </p>

            <SubTitle>9.3 Commission Approval</SubTitle>
            <p className="pl-11 mb-3">
              Commission calculations displayed within the Partner Dashboard are preliminary estimates only. Before any payment is issued, NexaHome reserves the right to review transactions for:
            </p>
            <ul className="space-y-2 pl-[54px] mb-4">
              {[
                "fraudulent activity",
                "duplicate referrals",
                "system errors",
                "reversed transactions",
                "chargebacks",
                "refunds",
                "abuse of the referral program",
                "violations of these Partner Terms",
                "compliance with the executed Partner Agreement",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="pl-11 mb-6">
              Only commissions approved through NexaHome’s internal accounting process become payable.
            </p>

            <SubTitle>9.4 Taxes</SubTitle>
            <p className="pl-11 mb-6">
              Partners are solely responsible for determining, reporting, and paying all applicable federal, state, and local taxes arising from commission payments received through the Partner Program. NexaHome does not provide tax advice. Where required by law, NexaHome may collect tax documentation and report payments to applicable governmental authorities.
            </p>

            <SubTitle>9.5 Payment Delays</SubTitle>
            <p className="pl-11 mb-3">
              NexaHome may delay, withhold, offset, or deny commission payments where reasonably necessary to:
            </p>
            <ul className="space-y-2 pl-[54px]">
              {[
                "investigate suspected fraud",
                "comply with applicable laws",
                "resolve disputes",
                "satisfy legal obligations",
                "correct accounting errors",
                "recover overpayments",
                "address payment processor issues",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="pl-11 mt-4">
              Nothing in these Partner Terms requires NexaHome to make payment before completion of such review.
            </p>
          </div>

          <Divider />

          {/* Section 10 */}
          <div>
            <SectionTitle number="10" title="Marketing and Branding Guidelines" />
            <p className="mb-4">
              Partners are granted a limited, revocable, non-exclusive, non-transferable license to use approved NexaHome marketing materials solely for participation in the Partner Program. Partners may use only marketing materials, logos, trademarks, graphics, and promotional content expressly approved by NexaHome.
            </p>
            <p className="mb-3">
              Partners shall not:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "alter the NexaHome logo",
                "create derivative branding",
                "imply ownership of NexaHome",
                "present themselves as employees or agents of NexaHome",
                "represent that NexaHome endorses their organization beyond participation in the Partner Program",
                "register domain names, business names, or social media accounts confusingly similar to NexaHome",
                "issue press releases regarding NexaHome without prior written approval",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              NexaHome may update branding guidelines at any time. Partners agree to immediately discontinue use of any materials that NexaHome requests be removed.
            </p>
          </div>

          <Divider />

          {/* Section 11 */}
          <div>
            <SectionTitle number="11" title="Acceptable Use and Prohibited Conduct" />
            <p className="mb-3">
              Partners agree to use the Partner Platform only for lawful purposes and in accordance with these Partner Terms. Without limitation, Partners shall not:
            </p>
            <ul className="space-y-2 pl-1 mb-6">
              {[
                "submit false or misleading information",
                "create fraudulent referrals",
                "generate artificial traffic",
                "create duplicate User accounts",
                "encourage Users to violate Platform policies",
                "interfere with referral tracking systems",
                "manipulate commission calculations",
                "use bots, scripts, crawlers, or automated software",
                "attempt to bypass security measures",
                "upload malicious software or code",
                "access data belonging to other Partners",
                "interfere with Platform performance",
                "impersonate another individual or organization",
                "misuse confidential information",
                "engage in deceptive advertising",
                "violate intellectual property rights",
                "violate any applicable law",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-3">
              Partners shall not use referral links in connection with:
            </p>
            <ul className="space-y-2 pl-1 mb-6">
              {[
                "spam email campaigns",
                "unsolicited text messaging",
                "robocalls",
                "deceptive advertising",
                "fraudulent websites",
                "malware",
                "phishing campaigns",
                "illegal products or services",
                "unlawful telemarketing activities",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Partners are solely responsible for ensuring their marketing activities comply with all applicable laws, including consumer protection, advertising, privacy, and anti-spam regulations (including, where applicable, the CAN-SPAM Act and the Telephone Consumer Protection Act (TCPA)).
            </p>
          </div>

          <Divider />

          {/* Section 12 */}
          <div>
            <SectionTitle number="12" title="Ownership of Data" />
            <p className="mb-3">
              All Platform data remains the exclusive property of NexaHome. This includes, without limitation:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "User information",
                "Expert information",
                "referral data",
                "commission data",
                "analytics",
                "reports",
                "Platform metrics",
                "software",
                "databases",
                "algorithms",
                "business intelligence",
                "operational data",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-6">
              Partners receive only a limited right to view information made available through the Partner Dashboard. No ownership rights are transferred to Partners.
            </p>
            <p className="mb-3">
              Partners may not:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "copy Platform databases",
                "reproduce analytics",
                "create competing databases",
                "commercialize Platform information",
                "sell dashboard data",
                "disclose confidential reports without authorization",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Upon termination of participation in the Partner Program, all rights to access Platform data immediately cease.
            </p>
          </div>

          <Divider />

          {/* Section 13 */}
          <div>
            <SectionTitle number="13" title="Intellectual Property" />
            <p className="mb-3">
              The NexaHome Platform, Partner Dashboard, software, website, mobile applications, trademarks, service marks, logos, graphics, content, databases, source code, object code, documentation, and all related intellectual property are owned exclusively by NexaHome or its licensors. Nothing contained within these Partner Terms transfers ownership of any intellectual property. Except as expressly authorized in writing, Partners may not:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "reproduce",
                "distribute",
                "modify",
                "reverse engineer",
                "decompile",
                "create derivative works",
                "publicly display",
                "publicly perform",
                "sublicense",
                "lease",
                "sell",
                "or otherwise exploit any portion of the Platform",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Any feedback, suggestions, recommendations, or ideas submitted by Partners regarding improvements to the Platform may be used by NexaHome without restriction or compensation.
            </p>
          </div>

          <Divider />

          {/* Section 14 */}
          <div>
            <SectionTitle number="14" title="Confidentiality" />
            <p className="mb-3">
              During participation in the Partner Program, Partners may receive confidential or proprietary information concerning NexaHome’s business. Confidential Information includes, without limitation:
            </p>
            <ul className="space-y-2 pl-1 mb-6">
              {[
                "commission structures",
                "referral statistics",
                "Platform analytics",
                "software functionality",
                "financial information",
                "operational procedures",
                "marketing strategies",
                "business plans",
                "technical documentation",
                "internal communications",
                "product roadmaps",
                "non-public reports",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-3">
              Partners agree to:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "maintain the confidentiality of such information",
                "use Confidential Information solely for participation in the Partner Program",
                "restrict access to authorized personnel with a legitimate business need",
                "implement reasonable safeguards to protect Confidential Information",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              Partners shall not disclose Confidential Information to any third party without NexaHome’s prior written consent unless required by law. The confidentiality obligations contained in this Section survive termination of these Partner Terms.
            </p>
          </div>

          <Divider />

          {/* Section 15 */}
          <div>
            <SectionTitle number="15" title="Suspension and Termination" />
            <p className="mb-3">
              NexaHome reserves the right, in its sole discretion, to suspend, restrict, or terminate your access to the Partner Platform, the Partner Program, or any associated services at any time, with or without prior notice, if NexaHome reasonably determines that:
            </p>
            <ul className="space-y-2 pl-1 mb-6">
              {[
                "You have violated these Partner Terms",
                "You have breached any executed Partner Agreement or other agreement with NexaHome",
                "You have engaged in fraudulent, deceptive, or unlawful activity",
                "You have attempted to manipulate referral attribution, commission calculations, or Platform functionality",
                "Your conduct may harm NexaHome, its Users, Experts, other Partners, or the integrity of the Platform",
                "You have provided false or misleading information during registration or participation in the Partner Program",
                "Continued participation presents legal, regulatory, financial, or reputational risk to NexaHome",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-4">
              NexaHome may also suspend or terminate the Partner Program, or any portion thereof, at any time without liability. Termination of your participation in the Partner Program shall immediately revoke your right to access the Partner Dashboard, referral tools, analytics, and any other Partner-only functionality.
            </p>
            <p>
              Unless otherwise expressly provided in an executed Partner Agreement, termination does not entitle you to future commissions on activity occurring after your participation has ended. Termination shall not affect any rights or obligations that accrued prior to the effective date of termination.
            </p>
          </div>

          <Divider />

          {/* Section 16 */}
          <div>
            <SectionTitle number="16" title="Disclaimer of Warranties" />
            <div className="bg-primary/10 border border-primary/20 text-primary font-semibold text-sm px-4 py-3 rounded-lg uppercase tracking-wide space-y-4">
              <p>
                THE PARTNER PLATFORM, PARTNER PROGRAM, DASHBOARD, REFERRAL TOOLS, ANALYTICS, REPORTS, COMMISSION CALCULATIONS, AND ALL RELATED SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE.&rdquo;
              </p>
              <p>
                TO THE FULLEST EXTENT PERMITTED BY LAW, NEXAHOME DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, RELIABILITY, AVAILABILITY, SECURITY, UNINTERRUPTED ACCESS, AND ERROR-FREE OPERATION.
              </p>
              <p>
                NEXAHOME DOES NOT WARRANT THAT REFERRAL LINKS WILL ALWAYS TRACK SUCCESSFULLY; THAT COMMISSIONS WILL BE GENERATED; THAT USERS WILL REGISTER OR REMAIN ACTIVE; THAT EXPERTS WILL PURCHASE LEADS; THAT THE DASHBOARD WILL ALWAYS DISPLAY CURRENT OR COMPLETE INFORMATION; THAT THE PLATFORM WILL OPERATE WITHOUT INTERRUPTION; OR THAT DEFECTS WILL BE CORRECTED IMMEDIATELY.
              </p>
              <p>
                PARTNERS ASSUME ALL RISK ARISING FROM THEIR PARTICIPATION IN THE PARTNER PROGRAM.
              </p>
            </div>
          </div>

          <Divider />

          {/* Section 17 */}
          <div>
            <SectionTitle number="17" title="Limitation of Liability" />
            <div className="bg-primary/10 border border-primary/20 text-primary font-semibold text-sm px-4 py-3 rounded-lg uppercase tracking-wide space-y-4">
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEXAHOME, ITS MEMBERS, OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, CONTRACTORS, AGENTS, LICENSORS, AND SERVICE PROVIDERS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOST PROFITS, LOST COMMISSIONS, LOST BUSINESS OPPORTUNITIES, LOST DATA, LOSS OF GOODWILL, OR BUSINESS INTERRUPTION.
              </p>
              <p>
                THIS LIMITATION APPLIES REGARDLESS OF THE THEORY OF LIABILITY, INCLUDING CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE.
              </p>
              <p>
                TO THE EXTENT LIABILITY CANNOT BE EXCLUDED, NEXAHOME’S TOTAL AGGREGATE LIABILITY ARISING FROM OR RELATING TO THESE PARTNER TERMS SHALL NOT EXCEED THE TOTAL COMMISSIONS PAID OR PAYABLE TO YOU DURING THE SIX (6) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
              </p>
              <p>
                SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OF LIABILITY. IN SUCH JURISDICTIONS, LIABILITY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
              </p>
            </div>
          </div>

          <Divider />

          {/* Section 18 */}
          <div>
            <SectionTitle number="18" title="Indemnification" />
            <p className="mb-3">
              You agree to defend, indemnify, and hold harmless NexaHome, its members, officers, directors, employees, affiliates, agents, contractors, successors, and assigns from and against any and all claims, actions, damages, losses, liabilities, judgments, settlements, penalties, fines, costs, and expenses, including reasonable attorneys&rsquo; fees, arising out of or relating to:
            </p>
            <ul className="space-y-2 pl-1 mb-4">
              {[
                "your participation in the Partner Program",
                "your violation of these Partner Terms",
                "your breach of any executed Partner Agreement",
                "your marketing or promotional activities",
                "misuse of referral links",
                "violation of applicable laws or regulations",
                "infringement of any third-party intellectual property rights",
                "false advertising or deceptive business practices",
                "unauthorized use of Platform data",
                "negligence or willful misconduct by you or your representatives",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p>
              NexaHome reserves the right to assume exclusive control of the defense of any matter subject to indemnification, and you agree to cooperate fully with such defense.
            </p>
          </div>

          <Divider />

          {/* Section 19 */}
          <div>
            <SectionTitle number="19" title="Governing Law; Jurisdiction; Class Action Waiver" />
            <p className="mb-4">
              These Partner Terms shall be governed by and construed in accordance with the laws of the State of Louisiana, without regard to its conflict-of-law principles.
            </p>
            <p className="mb-4">
              Before initiating any legal proceeding, the parties agree to attempt informal resolution by contacting{" "}
              <a href="mailto:info@nexahomeapp.com" className="text-primary underline underline-offset-2 hover:text-primary-dark transition-colors font-medium">
                info@nexahomeapp.com
              </a>{" "}
              and allowing at least thirty (30) days to resolve the dispute.
            </p>
            <p className="mb-4">
              If a dispute cannot be resolved informally, any legal action arising from or relating to these Partner Terms shall be brought exclusively in the state or federal courts located within the State of Louisiana. Each party irrevocably submits to the exclusive jurisdiction and venue of those courts. Nothing in this Section prevents either party from seeking temporary or permanent injunctive relief where appropriate.
            </p>
            <div className="bg-primary/10 border border-primary/20 text-primary font-semibold text-sm px-4 py-3 rounded-lg uppercase tracking-wide space-y-4">
              <p>YOU AND NEXAHOME EACH WAIVE THE RIGHT TO A TRIAL BY JURY.</p>
              <p>YOU AND NEXAHOME FURTHER AGREE THAT ANY CLAIM SHALL BE BROUGHT ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE ACTION.</p>
            </div>
          </div>

          <Divider />

          {/* Section 20 */}
          <div>
            <SectionTitle number="20" title="Modifications" />
            <p className="mb-4">
              NexaHome reserves the right to modify these Partner Terms at any time. Updated versions will be posted on the Partner Platform with a revised Effective Date. For material changes, NexaHome may also provide notice through the Partner Dashboard, email, Platform notifications, or other reasonable communication methods.
            </p>
            <p>
              Continued use of the Partner Platform following the effective date of revised Partner Terms constitutes acceptance of those revisions. If you do not agree to the updated Partner Terms, your sole remedy is to discontinue participation in the Partner Program.
            </p>
          </div>

          <Divider />

          {/* Section 21 */}
          <div>
            <SectionTitle number="21" title="Miscellaneous" />
            <p className="mb-4">
              If any provision of these Partner Terms is determined to be invalid, illegal, or unenforceable, the remaining provisions shall remain in full force and effect. Failure by NexaHome to enforce any provision shall not constitute a waiver of future enforcement.
            </p>
            <p className="mb-4">
              Partners may not assign, transfer, sublicense, or delegate any rights or obligations under these Partner Terms without NexaHome’s prior written consent. NexaHome may assign these Partner Terms without restriction in connection with a merger, acquisition, corporate restructuring, financing transaction, or sale of assets.
            </p>
            <p className="mb-4">
              These Partner Terms, together with the Partner Privacy Policy and any executed Partner Agreement, constitute the entire understanding between the parties concerning the Partner Platform. In the event of a conflict regarding commission percentages, payment schedules, or other commercial terms, the executed Partner Agreement shall control.
            </p>
            <p>
              The following Sections survive termination: Section 12 (Ownership of Data), Section 13 (Intellectual Property), Section 14 (Confidentiality), Section 16 (Disclaimer of Warranties), Section 17 (Limitation of Liability), Section 18 (Indemnification), Section 19 (Governing Law; Jurisdiction; Class Action Waiver), and Section 21 (Miscellaneous).
            </p>
          </div>

          <Divider />

          {/* Section 22 */}
          <div>
            <SectionTitle number="22" title="Contact Information" />
            <div className="bg-gray-50 border border-gray-200 rounded-xl px-6 py-5 space-y-2 text-sm">
              <p className="font-semibold text-gray-900 text-base">NexaHome, LLC</p>
              <p>
                <span className="text-gray-500">Email: </span>
                <a
                  href="mailto:info@nexahomeapp.com"
                  className="text-primary underline underline-offset-2 hover:text-primary-dark transition-colors font-medium"
                >
                  info@nexahomeapp.com
                </a>
              </p>
              <p>
                <span className="text-gray-500">Website: </span>
                <a
                  href="https://www.nexahomeapp.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-2 hover:text-primary-dark transition-colors font-medium"
                >
                  www.nexahomeapp.com
                </a>
              </p>
            </div>
          </div>

          {/* Footer note */}
          <p className="text-xs text-gray-400 border-t border-gray-200 pt-8">
            © 2026 NexaHome, LLC. All rights reserved.
          </p>

        </section>
      </main>

      <Footer />
    </>
  );
}

/* ── Reusable micro-components ── */

function SectionTitle({ number, title }) {
  return (
    <div className="flex items-center gap-3 mb-4">
      <span className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-white text-sm font-bold flex items-center justify-center">
        {number}
      </span>
      <h2 className="text-xl md:text-2xl font-bold text-primary">{title}</h2>
    </div>
  );
}

function SubTitle({ children }) {
  return (
    <h3 className="text-[15px] font-semibold text-gray-900 mb-2 mt-4 pl-11">
      {children}
    </h3>
  );
}

function Divider() {
  return <hr className="border-gray-100" />;
}
